const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={chats:[],active:null,attachment:null,web:false,imageMode:false,generating:false,settings:{provider:'puter',endpoint:'http://localhost:11434',model:'gpt-5.4-nano',systemPrompt:'Ты NOVA — полезный, точный и дружелюбный AI-ассистент. Отвечай на языке пользователя.',interfaceTheme:'dark',interfaceScale:'100',interfaceDensity:'comfortable',interfaceAnimations:true,privacyHistory:true}};
const uid=()=>crypto.randomUUID?.()||Date.now().toString(36); const escapeHtml=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function getSystemPrompt(){return `Тебя зовут Nova AI. Если пользователь спрашивает, как тебя зовут, кто ты или как к тебе обращаться, ответь точно: «Я Nova AI. Можешь звать меня просто Nova, если так удобнее.» Не называй себя именем модели, провайдера или другим именем. Для актуальных или меняющихся данных обязательно используй веб-поиск, указывай дату проверки и приводи ссылки на источники. Не выдавай приблизительные или устаревшие данные за статистику в реальном времени. Если платформа скрывает точное значение, прямо скажи об этом.\n\n${window.NOVA_RESPONSE_SYSTEM_PROMPT||''}\n\n${state.settings.systemPrompt}`}
function needsLiveSearch(text){return /(?:сколько|подписчик|фолловер|просмотр|онлайн|статистик|youtube|ютуб|tiktok|тикток|twitch|твич|instagram|инстаграм|новост|сегодня|сейчас|актуальн|последн|курс|цен[аы]|погод|результат|сч[её]т|расписани|кто сейчас|реальн(?:ом|ое) времен)/i.test(text)}
function needsP2PArmy(text){return /(?:p2p|п2п|крипт|usdt|usdc|btc|eth|binance|bybit|okx|mexc|htx|bitget|gate|bingx|kucoin).*(?:курс|рын|рин|цен|спред|объявлен|об[ъь]ем|фиат|покуп|продаж|арбитраж)|(?:курс|рын|рин|цен|спред|объявлен|об[ъь]ем|фиат|покуп|продаж|арбитраж).*(?:p2p|п2п|крипт|usdt|usdc|btc|eth|binance|bybit|okx|mexc|htx|bitget|gate|bingx|kucoin)/i.test(text)}
function p2pArmyInstruction(){return `Это запрос о текущем P2P-рынке. При КАЖДОМ таком запросе обязательно включи интернет-поиск и заново проверь P2P.Army; не отвечай цифрами из памяти или старого чата. Главные страницы: https://p2p.army/ru/p2p/markets (биржи и рынок), https://p2p.army/ru/p2p/currencies (валюты, курс USDT, изменение 24ч, объявления и объемы), https://p2p.army/ru/p2p/prices/ (BUY/SELL по бирже и способу оплаты) и https://p2p.army/ru/p2p/spreads/ (спреды). Используй только свежие данные P2P.Army и прямую страницу выбранной пары. Определи актив, фиат, биржу, сторону и банк/способ оплаты. Показывай только показатели, нужные для вопроса: текущий курс; BUY и SELL; спред в валюте и процентах; изменение за 24ч; количество BUY/SELL объявлений; BUY/SELL и общий объем; активность 24ч; долю и количество бирж — но не перечисляй всё, если этого не просили. Краткий формат для обычного вопроса о курсе: «АКТИВ → ФИАТ · проверено ДД.ММ.ГГГГ ЧЧ:ММ»; «Биржа / банк: BUY X · SELL Y»; «Спред: X (Y%)»; «Ориентир: 1 АКТИВ ≈ A–B ФИАТ»; одна прямая Markdown-ссылка на P2P.Army. BUY — цена покупки актива пользователем, SELL — цена продажи актива пользователем. Если биржа не указана, сравни максимум 3 биржи и попроси выбрать одну. Не добавляй общую теорию. Никогда не называй число актуальным, если оно не получено при текущей интернет-проверке. Если динамическая таблица или свежие числа недоступны, напиши «Не удалось получить свежие значения P2P.Army» и дай прямую ссылку; ничего не выдумывай. Учитывай, что сами P2P.Army называют индексированные данные приблизительными.`}
function p2pInternetInstruction(){return window.novaMarketInstruction?window.novaMarketInstruction():`Ищи актуальные рыночные данные по всему открытому интернету, прежде всего в официальных источниках бирж. Не используй P2P.Army.`}
function applyInterface(){const s=state.settings,t=s.interfaceTheme||'dark',systemDark=matchMedia?.('(prefers-color-scheme: dark)').matches;document.documentElement.dataset.theme=t==='system'?(systemDark?'dark':'light'):t;document.documentElement.dataset.density=s.interfaceDensity||'comfortable';document.documentElement.dataset.reduceMotion=s.interfaceAnimations===false?'true':'false';document.documentElement.style.setProperty('--nova-ui-scale',(s.interfaceScale||'100')+'%');localStorage.setItem('nova.theme',t)}
function load(){try{const saved=JSON.parse(localStorage.getItem('nova.settings'))||{};Object.assign(state.settings,saved);state.chats=state.settings.privacyHistory===false?[]:JSON.parse(localStorage.getItem('nova.chats'))||[];if(!saved.provider){state.settings.provider='puter';state.settings.model='gpt-5.4-nano'}if(/gpt-5\.3-chat/i.test(state.settings.model)){state.settings.model='gpt-5.4-nano'}if(!saved.interfaceTheme)state.settings.interfaceTheme=localStorage.getItem('nova.theme')||'dark';localStorage.setItem('nova.settings',JSON.stringify(state.settings));applyInterface()}catch{} renderHistory();updateLabels()}
function save(){if(state.settings.privacyHistory===false)localStorage.removeItem('nova.chats');else localStorage.setItem('nova.chats',JSON.stringify(state.chats));renderHistory()}
function toast(message){const el=document.createElement('div');el.className='toast';el.textContent=message;$('#toasts').append(el);setTimeout(()=>el.remove(),3500)}
async function ensurePuterUsage(){if(!window.puter?.auth?.getMonthlyUsage)return;try{const usage=await puter.auth.getMonthlyUsage();const remaining=Number(usage?.allowanceInfo?.remaining);if(Number.isFinite(remaining)&&remaining<=0)throw new Error('NOVA_NO_USAGE')}catch(e){if(e?.message==='NOVA_NO_USAGE')throw new Error('Лимит Puter исчерпан. AI временно недоступен. Пополните лимит Puter или выберите локальный провайдер в настройках.')}}
function newChat(){state.active=null;state.attachment=null;$('#messages').innerHTML='';$('#welcome').hidden=false;$('#attachmentPreview').innerHTML='';closeSidebar();$('#prompt').focus();renderHistory()}
function getChat(){let chat=state.chats.find(c=>c.id===state.active);if(!chat){chat={id:uid(),title:'Новый диалог',created:Date.now(),messages:[]};state.chats.unshift(chat);state.active=chat.id}return chat}
function renderHistory(filter=''){const box=$('#history');const list=state.chats.filter(c=>c.title.toLowerCase().includes(filter.toLowerCase()));box.innerHTML=`<div class="history-group"><div class="history-label">НЕДАВНИЕ</div>${list.length?list.map(c=>`<button class="history-item ${c.id===state.active?'active':''}" data-chat="${c.id}">${escapeHtml(c.title)}</button>`).join(''):'<p class="history-label">Пока нет диалогов</p>'}</div>`;$$('[data-chat]',box).forEach(b=>b.onclick=()=>openChat(b.dataset.chat))}
function openChat(id){state.active=id;const chat=state.chats.find(c=>c.id===id);if(!chat)return;$('#welcome').hidden=true;$('#messages').innerHTML='';chat.messages.forEach(m=>addMessage(m.role,m.content,false));closeSidebar();renderHistory();scrollBottom()}
function addMessage(role,content,animate=true){$('#welcome').hidden=true;const el=document.createElement('div');el.className=`message ${role}`;el.innerHTML=role==='assistant'?`<span class="ai-avatar">✦</span><div><div class="bubble ${animate?'typing':''}">${escapeHtml(content)}</div><div class="message-meta">NOVA · локальная модель</div></div>`:`<div class="bubble">${escapeHtml(content)}</div>`;$('#messages').append(el);scrollBottom();return $('.bubble',el)}
function addGeneratedImage(src,prompt,asset={}){const el=document.createElement('div');el.className='message assistant';const name=`NOVA-AI-${new Date().toISOString().slice(0,10)}-${String(asset.version||1).padStart(3,'0')}.png`;el.innerHTML=`<span class="ai-avatar">✦</span><div class="generated-card"><img alt="${escapeHtml(prompt)}" src="${src}"><div class="generated-actions"><span>Версия ${asset.version||1} · ${escapeHtml(asset.sourceType||'IMAGE_GENERATE')}</span><a href="${src}" download="${name}" target="_blank" rel="noopener">Скачать</a><button type="button" data-image-edit>Изменить</button><button type="button" data-image-variation>Ещё вариант</button></div></div>`;$('#messages').append(el);$('[data-image-edit]',el).onclick=()=>{$('#prompt').placeholder='Что изменить?';$('#prompt').focus()};$('[data-image-variation]',el).onclick=()=>{$('#prompt').value='Сделай ещё один вариант';send()};scrollBottom()}
function addImageLoader(){const el=document.createElement('div');el.className='message assistant';el.innerHTML='<span class="ai-avatar">✦</span><div class="image-loading">Создаю изображение…</div>';$('#messages').append(el);scrollBottom();return el}
function scrollBottom(){$('#chat').scrollTop=$('#chat').scrollHeight}
function resizePrompt(){const p=$('#prompt');p.style.height='auto';p.style.height=Math.min(p.scrollHeight,150)+'px'}
async function send(){const input=$('#prompt'),text=input.value.trim();if((!text&&!state.attachment)||state.generating)return;const chat=getChat();const visible=text||(state.attachment?`Проанализируй файл: ${state.attachment.name}`:'');chat.messages.push({role:'user',content:visible});if(chat.messages.length===1)chat.title=visible.slice(0,46);addMessage('user',visible);input.value='';resizePrompt();state.generating=true;$('#sendBtn').disabled=true;if(window.NovaZip?.active){const z=await NovaZip.execute(visible);if(z?.handled){const bubble=addMessage('assistant',z.text,false);const card=document.createElement('div');card.className='attachment-chip';card.innerHTML=`<span>📦</span><span>${escapeHtml(z.name)}</span><a href="${z.url}" download="${escapeHtml(z.name)}">Скачать ZIP</a>`;bubble.append(card);chat.messages.push({role:'assistant',content:z.text+' '+z.changes.map(x=>x.path).join(', ')});state.generating=false;$('#sendBtn').disabled=false;save();return}}if(state.imageMode||window.NovaImages?.classify(visible,state,chat.id)){await generateImage(visible,chat);return}const bubble=addMessage('assistant','');
  try{let images=[];if(state.attachment?.type.startsWith('image/'))images=[state.attachment.data.split(',')[1]];const recentContext=chat.messages.slice(-12).map(m=>`${m.role}: ${m.content}`).join('\n');const p2pContext=needsP2PArmy(recentContext);let promptText=visible;if(state.attachment?.text)promptText+=`\n\nСодержимое файла:\n${state.attachment.text.slice(0,12000)}`;if(p2pContext)promptText+=`\n\nПродолжай тему предыдущих сообщений этого чата. Короткий запрос пользователя относится к ранее указанным активу, валюте, бирже и банку, пока он явно не сменил тему.\n${p2pInternetInstruction()}`;if(state.web&&state.settings.provider==='ollama')throw new Error('Интернет-поиск требует отдельного backend-провайдера. Отключите режим или выберите Puter Cloud.');
    const messages=[{role:'system',content:getSystemPrompt()},...chat.messages.slice(0,-1),{role:'user',content:promptText,...(images.length?{images}:{})}];let full='';
    if(state.settings.provider==='puter'){
      if(!window.puter?.ai)throw new Error('Облачный модуль не загрузился. Проверьте подключение к интернету.');
      await ensurePuterUsage();
      const liveSearch=state.web||needsLiveSearch(recentContext)||p2pContext;const options={model:state.settings.model||'gpt-5.4-nano',stream:true,...(liveSearch?{tools:[{type:'web_search'}]}:{})};
      const stream=state.attachment?.type.startsWith('image/')?await puter.ai.chat(promptText,state.attachment.data,options):await puter.ai.chat(messages,options);
      for await(const part of stream){if(part.type==='error')throw new Error(part.message||'Ошибка облачной модели');const text=part.text||(part.type==='text'?part.text:'')||'';full+=text;bubble.textContent=full;scrollBottom()}
    }else{
      const res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:state.settings.model,messages,stream:true})});if(!res.ok){let detail='';try{detail=(await res.json()).error||''}catch{}throw new Error(detail||`Ollama вернула ошибку ${res.status}`)}if(!res.body)throw new Error('Потоковый ответ недоступен');const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='';
      while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop();for(const line of lines){if(!line.trim())continue;const json=JSON.parse(line);full+=json.message?.content||'';bubble.textContent=full;scrollBottom()}}
    }
    bubble.classList.remove('typing');chat.messages.push({role:'assistant',content:full||'Модель не вернула текст.'});save();if(full&&'speechSynthesis' in window&&'SpeechSynthesisUtterance' in window&&localStorage.getItem('nova.autospeak')==='true')window.speechSynthesis.speak(new window.SpeechSynthesisUtterance(full));
  }catch(err){bubble.classList.remove('typing');const direct=location.protocol==='file:',detail=err?.message||err?.error||String(err||'Неизвестная ошибка авторизации'),noUsage=/no usage|usage left|low balance|funding|лимит puter|исчерпан/i.test(detail);bubble.textContent=direct?'NOVA нужно открыть через локальный сервер. Запустите start.bat, затем откройте http://localhost:8080.':noUsage?'Лимит облачного AI исчерпан. Пополните Puter или выберите локальный провайдер в настройках.':`Не удалось подключиться к AI. ${detail}`;bubble.parentElement.querySelector('.message-meta').textContent=noUsage?'Лимит провайдера исчерпан':'Провайдер не настроен или недоступен';toast(direct?'Запустите NOVA через start.bat':noUsage?'Недостаточно лимита Puter':'Завершите вход в Puter и повторите запрос');}
  finally{state.generating=false;$('#sendBtn').disabled=false;state.attachment=null;$('#attachmentPreview').innerHTML='';save()}}
async function generateImage(promptText,chat){const loader=addImageLoader();try{loader.querySelector('.image-loading').textContent='Подготавливаю…';const asset=await window.NovaImages.run(promptText,state,chat);loader.remove();addGeneratedImage(asset.url,promptText,asset);chat.messages.push({role:'assistant',content:`[Изображение ${asset.id}, версия ${asset.version}] ${promptText}`});save();toast('Изображение готово')}catch(err){loader.remove();const bubble=addMessage('assistant',`Не удалось создать изображение. ${err.message}`,false);bubble.parentElement.querySelector('.message-meta').textContent='Ошибка генерации изображения';toast('Генерация изображения не удалась')}finally{state.generating=false;$('#sendBtn').disabled=false;state.attachment=null;$('#attachmentPreview').innerHTML=''}}
function attach(){ $('#fileInput').click() }
async function handleFile(file){if(!file)return;if(/\.zip$/i.test(file.name)){try{toast('Проверяю ZIP…');const ws=await NovaZip.inspect(file);state.attachment={name:file.name,type:'application/zip',data:'',text:NovaZip.summary(ws)};renderAttachment();toast(`Архив проанализирован: ${ws.entries.length} элементов`)}catch(e){toast(e.message||'Не удалось открыть архив')}return}if(file.size>12*1024*1024){toast('Файл больше 12 МБ');return}const data=await new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)});let text='';if(file.type.startsWith('text/')||/\.(md|json|csv)$/i.test(file.name))text=await file.text();state.attachment={name:file.name,type:file.type||'application/octet-stream',data,text};renderAttachment()}
function renderAttachment(){const a=state.attachment;$('#attachmentPreview').innerHTML=a?`<div class="attachment-chip">${a.type.startsWith('image/')?`<img src="${a.data}" alt="">`:'<span>⌑</span>'}<span>${escapeHtml(a.name)}</span><button id="removeAttachment">×</button></div>`:'';if(a)$('#removeAttachment').onclick=()=>{state.attachment=null;renderAttachment()}}
function toggleWeb(){state.web=!state.web;$('#webBtn').classList.toggle('active',state.web);toast(state.web?'Интернет-поиск включён — требуется backend-провайдер':'Интернет-поиск выключен')}
function toggleImageMode(force){state.imageMode=typeof force==='boolean'?force:!state.imageMode;$('#imageBtn').classList.toggle('active',state.imageMode);if(state.imageMode){state.web=false;$('#webBtn').classList.remove('active');$('#prompt').placeholder='Опишите изображение, которое хотите создать...';toast('Режим генерации изображений включён')}else $('#prompt').placeholder='Спросите что угодно...'}
function selectSettingsTab(name){$$('[data-settings-tab]').forEach(x=>x.classList.toggle('active',x.dataset.settingsTab===name));$$('[data-settings-panel]').forEach(x=>x.classList.toggle('active',x.dataset.settingsPanel===name))}
function settings(){const s=state.settings;$('#provider').value=s.provider||'puter';$('#endpoint').value=s.endpoint;$('#model').value=s.model;$('#systemPrompt').value=s.systemPrompt;$('#interfaceTheme').value=s.interfaceTheme||'dark';$('#interfaceScale').value=s.interfaceScale||'100';$('#interfaceDensity').value=s.interfaceDensity||'comfortable';$('#interfaceAnimations').checked=s.interfaceAnimations!==false;$('#privacyHistory').checked=s.privacyHistory!==false;selectSettingsTab('ai');syncProviderFields();$('#settingsModal').showModal()}
function saveSettings(e){e.preventDefault();Object.assign(state.settings,{provider:$('#provider').value,endpoint:$('#endpoint').value.trim(),model:$('#model').value.trim(),systemPrompt:$('#systemPrompt').value.trim(),interfaceTheme:$('#interfaceTheme').value,interfaceScale:$('#interfaceScale').value,interfaceDensity:$('#interfaceDensity').value,interfaceAnimations:$('#interfaceAnimations').checked,privacyHistory:$('#privacyHistory').checked});localStorage.setItem('nova.settings',JSON.stringify(state.settings));applyInterface();save();updateLabels();$('#settingsModal').close();toast('Настройки сохранены')}
function exportData(){const payload={app:'NOVA AI',exportedAt:new Date().toISOString(),settings:state.settings,chats:state.chats};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='nova-ai-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Данные экспортированы')}
function clearHistory(){if(!confirm('Удалить всю историю чатов без возможности восстановления?'))return;state.chats=[];state.active=null;localStorage.removeItem('nova.chats');newChat();toast('История удалена')}
function syncProviderFields(){const cloud=$('#provider').value==='puter';$('#endpointField').hidden=cloud;$('#privacyTitle').textContent=cloud?'Облачная обработка':'Обрабатывается локально';$('#privacyText').textContent=cloud?'Puter выполняет AI-запросы без API-ключа разработчика. История NOVA хранится в этом браузере.':'Запросы отправляются только в локальный Ollama. История хранится в этом браузере.';if(cloud&&/^llama/.test($('#model').value))$('#model').value='gpt-5.4-nano';if(!cloud&&/^gpt-/.test($('#model').value))$('#model').value='llama3.2'}
function updateLabels(){$('#modelLabel').textContent=state.settings.provider==='ollama'?(state.settings.model||'NOVA Local'):'nova-1.0-nano';$('#providerLabel').textContent=state.settings.provider==='ollama'?'Ollama · локально':'Puter · облако'}
function search(){$('#searchModal').showModal();$('#searchInput').value='';renderSearch('');setTimeout(()=>$('#searchInput').focus(),50)}
function renderSearch(q){const list=state.chats.filter(c=>!q||c.title.toLowerCase().includes(q.toLowerCase())||c.messages.some(m=>m.content.toLowerCase().includes(q.toLowerCase())));$('#searchResults').innerHTML=list.length?list.map(c=>`<div class="search-result" data-result="${c.id}"><b>${escapeHtml(c.title)}</b><small>${c.messages.length} сообщений</small></div>`).join(''):'<div class="search-result">Ничего не найдено</div>';$$('[data-result]').forEach(x=>x.onclick=()=>{$('#searchModal').close();openChat(x.dataset.result)})}
function voice(){if(window.novaVoice)window.novaVoice.open();else toast('Голосовой режим ещё загружается')}
function closeSidebar(){$('#sidebar').classList.remove('open');$('#backdrop').classList.remove('active')}
$('#composer').onsubmit=e=>{e.preventDefault();send()};$('#prompt').oninput=resizePrompt;$('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};$('#attachBtn').onclick=attach;$('#fileInput').onchange=e=>handleFile(e.target.files[0]);$('#webBtn').onclick=toggleWeb;$('#imageBtn').onclick=()=>toggleImageMode();$('#micBtn').onclick=voice;$('#themeBtn').onclick=()=>{state.settings.interfaceTheme=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('nova.settings',JSON.stringify(state.settings));applyInterface()};
$('#collapseBtn').onclick=()=>$('#sidebar').classList.toggle('collapsed');$('#menuBtn').onclick=()=>{$('#sidebar').classList.add('open');$('#backdrop').classList.add('active')};$('#backdrop').onclick=closeSidebar;$('#saveSettings').onclick=saveSettings;$('#provider').onchange=syncProviderFields;$('#searchInput').oninput=e=>renderSearch(e.target.value);$$('[data-settings-tab]').forEach(b=>b.onclick=()=>selectSettingsTab(b.dataset.settingsTab));$('#exportDataBtn').onclick=exportData;$('#clearHistoryBtn').onclick=clearHistory;$('#interfaceTheme').onchange=()=>{state.settings.interfaceTheme=$('#interfaceTheme').value;applyInterface()};$('#interfaceScale').onchange=()=>{state.settings.interfaceScale=$('#interfaceScale').value;applyInterface()};$('#interfaceDensity').onchange=()=>{state.settings.interfaceDensity=$('#interfaceDensity').value;applyInterface()};$('#interfaceAnimations').onchange=()=>{state.settings.interfaceAnimations=$('#interfaceAnimations').checked;applyInterface()};
document.addEventListener('click',e=>{const b=e.target.closest('[data-action],[data-prompt],[data-tool],[data-close]');if(!b)return;if(b.dataset.prompt){$('#prompt').value=b.dataset.prompt;if(b.dataset.imageMode)toggleImageMode(true);resizePrompt();$('#prompt').focus()}if(b.dataset.action==='new-chat')newChat();if(b.dataset.action==='settings')settings();if(b.dataset.action==='search')search();if(b.dataset.action==='attach')attach();if(b.dataset.action==='voice')voice();if(b.dataset.tool==='images'){toggleImageMode(true);$('#prompt').focus()}if(b.dataset.tool==='files')attach();if(b.dataset.tool==='internet')toggleWeb();if(b.dataset.close)$('#'+b.dataset.close).close()});
document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='k'){e.preventDefault();search()}if(e.ctrlKey&&e.key.toLowerCase()==='n'){e.preventDefault();newChat()}if(e.key==='Escape'&&state.generating)toast('Остановка потока будет доступна после подключения AbortController')});
if(window.visualViewport){document.body.style.setProperty('--vvh',window.visualViewport.height+'px');window.visualViewport.addEventListener('resize',()=>{document.body.style.setProperty('--vvh',window.visualViewport.height+'px')})}
document.addEventListener('dragover',e=>e.preventDefault());document.addEventListener('drop',e=>{e.preventDefault();handleFile(e.dataTransfer.files[0])});document.addEventListener('paste',e=>{const f=[...e.clipboardData.files].find(x=>x.type.startsWith('image/'));if(f)handleFile(f)});load();
