(()=>{
  const q=s=>document.querySelector(s), layer=q('#voiceLayer');
  const mode={active:false,muted:false,busy:false,speaking:false,recognition:null,stream:null,audioContext:null,analyser:null,vadFrame:0,bargeSince:0,history:[],speechQueue:[],speakingQueue:false,currentAudio:null,turn:0,cloudSTT:false,recorder:null,audioChunks:[],heardSpeech:false,lastVoiceAt:0,recordStartedAt:0};
  const setState=(name,title,sub='')=>{layer.dataset.state=name;q('#voiceKicker').textContent=({listening:'МИКРОФОН АКТИВЕН',thinking:'ОБРАБАТЫВАЮ ЗАПРОС',speaking:'ГОВОРЮ',muted:'МИКРОФОН ВЫКЛЮЧЕН',error:'НУЖНО ВНИМАНИЕ'})[name]||'NOVA VOICE';q('#voiceStatus').textContent=title;q('#voiceInterim').textContent=sub};
  const addTranscript=(role,text)=>{mode.history.push({role,content:text});const box=q('#transcriptList');q('.transcript-empty')?.remove();const el=document.createElement('div');el.className=`transcript-item ${role==='user'?'user':'ai'}`;el.innerHTML=`<b>${role==='user'?'ВЫ':'NOVA'}</b><span></span>`;el.querySelector('span').textContent=text;box.append(el);box.scrollTop=box.scrollHeight};
  async function open(){if(mode.active)return;const SR=window.SpeechRecognition||window.webkitSpeechRecognition;try{mode.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});mode.active=true;mode.cloudSTT=Boolean(window.NOVA_DESKTOP)||Boolean(window.NOVA_MOBILE)||!SR;layer.classList.add('active');document.body.style.overflow='hidden';setupAnalyser();if(!mode.cloudSTT&&SR)setupRecognition(SR);startListening()}catch{setState('error','Нет доступа к микрофону','Разрешите использование микрофона в настройках браузера');layer.classList.add('active')}}
  function setupRecognition(SR){const r=new SR();r.lang='ru-RU';r.continuous=true;r.interimResults=true;r.onresult=e=>{let interim='',final='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript.trim();if(e.results[i].isFinal)final+=t;else interim+=t}if(interim)q('#voiceInterim').textContent=interim;if(final&&!mode.busy&&!mode.muted)handleUser(final)};r.onend=()=>{if(mode.active&&!mode.muted&&!mode.speaking)setTimeout(startRecognition,180)};r.onerror=e=>{if(!['aborted','no-speech'].includes(e.error))setState('error','Не слышу микрофон',e.error)};mode.recognition=r}
  function startRecognition(){try{mode.recognition?.start()}catch{}}
  function stopRecognition(){try{mode.recognition?.abort()}catch{}}
  function startInput(){if(mode.cloudSTT)startCloudCapture();else startRecognition()}
  function stopInput(){if(mode.cloudSTT){if(mode.recorder?.state==='recording'){mode.recorder.onstop=null;mode.recorder.stop()}mode.recorder=null}else stopRecognition()}
  function startListening(){if(!mode.active||mode.muted)return;mode.busy=false;mode.speaking=false;setState('listening','Слушаю…',mode.cloudSTT?'Говорите — пауза отправит фразу автоматически':'Говорите — отправлять ничего не нужно');startInput()}
  function startCloudCapture(){if(!mode.active||mode.muted||mode.busy||mode.recorder?.state==='recording')return;try{const type=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm';mode.audioChunks=[];mode.heardSpeech=false;mode.lastVoiceAt=0;mode.recordStartedAt=performance.now();const recorder=new MediaRecorder(mode.stream,{mimeType:type});mode.recorder=recorder;recorder.ondataavailable=e=>{if(e.data.size)mode.audioChunks.push(e.data)};recorder.onstop=transcribeCloudAudio;recorder.start(250)}catch(err){setState('error','Не удалось включить запись',err.message)}}
  async function transcribeCloudAudio(){if(!mode.active||!mode.heardSpeech)return;mode.busy=true;setState('thinking','Распознаю речь…','Обрабатываю вашу фразу');try{if(!window.puter?.ai?.speech2txt)throw new Error('Облачное распознавание недоступно');const blob=new Blob(mode.audioChunks,{type:'audio/webm'});const result=await puter.ai.speech2txt(blob,{model:'gpt-4o-mini-transcribe',language:'ru',response_format:'json'});const text=(typeof result==='string'?result:result?.text||'').trim();if(!text)throw new Error('Речь не распознана');await handleUser(text)}catch(err){setState('error','Не удалось распознать речь',err.message||String(err));setTimeout(()=>mode.active&&!mode.muted&&startListening(),1600)}}
  async function handleUser(text){const turn=++mode.turn;mode.busy=true;stopRecognition();cancelSpeech();addTranscript('user',text);setState('thinking',needsLiveSearch(text)?'Ищу актуальные данные…':'Думаю…',text);const chat=typeof getChat==='function'?getChat():null;if(chat){chat.messages.push({role:'user',content:text});if(chat.messages.length===1)chat.title=text.slice(0,46);addMessage('user',text)}try{if(!window.puter?.ai)throw new Error('Нет подключения к облачному AI');const liveSearch=needsLiveSearch(text);const voicePrompt=getSystemPrompt()+'\n\nСейчас идёт голосовой разговор. Отвечай сразу по существу, обычно одним-тремя короткими разговорными предложениями. Не используй вступления, Markdown, звёздочки, списки, заголовки, таблицы и блоки кода. Для меняющихся данных используй веб-поиск, называй дату проверки и не выдумывай точные числа, если источник их не показывает.';const messages=[{role:'system',content:voicePrompt},...mode.history];const stream=await puter.ai.chat(messages,{model:state.settings.model||'gpt-5.4-nano',stream:true,...(liveSearch?{tools:[{type:'web_search'}]}:{})});let full='',sentence='';setState('speaking','Готовлю ответ…','Начну говорить через мгновение');mode.speaking=true;for await(const part of stream){if(turn!==mode.turn)return;const chunk=part.text||'';if(!chunk)continue;full+=chunk;sentence+=chunk;const ready=sentence.match(/^([\s\S]*?[.!?;:](?:\s|$))/);if(ready){setState('speaking','Отвечаю…','Можно перебить меня в любой момент');enqueueSpeech(ready[1]);sentence=sentence.slice(ready[1].length)}}if(turn!==mode.turn)return;if(sentence.trim())enqueueSpeech(sentence);await waitForSpeech();if(turn!==mode.turn)return;if(full){addTranscript('assistant',full);if(chat){chat.messages.push({role:'assistant',content:full});addMessage('assistant',full,false);save()}}if(mode.active&&!mode.muted)startListening()}catch(err){if(turn!==mode.turn)return;addTranscript('assistant',`Ошибка: ${err.message}`);setState('error','Не удалось ответить',err.message);setTimeout(()=>mode.active&&startListening(),1800)}}
  function cleanForSpeech(text){return text.replace(/```[\s\S]*?```/g,' фрагмент кода ').replace(/`([^`]+)`/g,'$1').replace(/!\[([^\]]*)\]\([^)]*\)/g,'$1').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/[*_~#>|]/g,'').replace(/^\s*[-+]\s+/gm,'').replace(/^\s*\d+[.)]\s+/gm,'').replace(/\s+/g,' ').trim()}
  function enqueueSpeech(text){const clean=cleanForSpeech(text);if(!clean)return;mode.speechQueue.push(clean);playNext()}
  async function playNext(){if(mode.speakingQueue||!mode.speechQueue.length||!mode.active)return;mode.speakingQueue=true;const text=mode.speechQueue.shift();try{if((window.NOVA_DESKTOP||window.NOVA_MOBILE||!hasSystemVoice())&&window.puter?.ai?.txt2speech){const audio=await puter.ai.txt2speech(text,{provider:'openai',model:'gpt-4o-mini-tts',voice:'nova',response_format:'mp3',instructions:'Говори по-русски естественно, спокойно и дружелюбно. Чёткое произношение, чуть быстрее средней скорости.'});if(!mode.active)throw new Error('stopped');mode.currentAudio=audio;await new Promise((resolve,reject)=>{audio.onended=resolve;audio.onerror=reject;audio.play().catch(reject)})}else await playSystemVoice(text)}catch{if(mode.active&&hasSystemVoice())await playSystemVoice(text)}finally{mode.currentAudio=null;mode.speakingQueue=false;playNext()}}
  function hasSystemVoice(){return 'speechSynthesis' in window&&'SpeechSynthesisUtterance' in window}
  function playSystemVoice(text){return new Promise(resolve=>{if(!hasSystemVoice())return resolve();const u=new window.SpeechSynthesisUtterance(text);u.lang='ru-RU';u.rate=.98;u.pitch=1;const voices=window.speechSynthesis.getVoices();u.voice=voices.find(v=>/^ru(?:-|_)/i.test(v.lang))||voices.find(v=>/russian|ирина|павел|светлана/i.test(v.name))||null;u.onend=u.onerror=resolve;window.speechSynthesis.speak(u)})}
  function cancelSpeech(){mode.currentAudio?.pause();if(mode.currentAudio)mode.currentAudio.currentTime=0;mode.currentAudio=null;if(hasSystemVoice())window.speechSynthesis.cancel();mode.speechQueue.length=0;mode.speakingQueue=false}
  function waitForSpeech(){return new Promise(resolve=>{const check=()=>{const systemSpeaking=hasSystemVoice()&&window.speechSynthesis.speaking;if(!mode.active||(!mode.speakingQueue&&!mode.speechQueue.length&&!systemSpeaking&&!mode.currentAudio))resolve();else setTimeout(check,100)};check()})}
  function setupAnalyser(){const AC=window.AudioContext||window.webkitAudioContext;mode.audioContext=new AC();const src=mode.audioContext.createMediaStreamSource(mode.stream);mode.analyser=mode.audioContext.createAnalyser();mode.analyser.fftSize=512;src.connect(mode.analyser);monitorLevel()}
  function monitorLevel(){if(!mode.active)return;const data=new Uint8Array(mode.analyser.fftSize);mode.analyser.getByteTimeDomainData(data);let sum=0;for(const v of data){const n=(v-128)/128;sum+=n*n}const rms=Math.sqrt(sum/data.length),now=performance.now();layer.style.setProperty('--voice-scale',String(1+Math.min(rms*3.5,.18)));if(mode.cloudSTT&&!mode.speaking&&!mode.busy&&!mode.muted&&mode.recorder?.state==='recording'){if(rms>.012){mode.heardSpeech=true;mode.lastVoiceAt=now;q('#voiceInterim').textContent='Слышу вас…'}if(mode.heardSpeech&&now-mode.lastVoiceAt>650&&now-mode.recordStartedAt>500)mode.recorder.stop()}if(mode.speaking&&rms>.08){if(!mode.bargeSince)mode.bargeSince=now;if(now-mode.bargeSince>260)bargeIn()}else mode.bargeSince=0;mode.vadFrame=requestAnimationFrame(monitorLevel)}
  function bargeIn(){mode.turn++;cancelSpeech();mode.speaking=false;mode.busy=false;mode.bargeSince=0;setState('listening','Слушаю…','Вы перебили NOVA — говорите');startInput()}
  function toggleMute(){mode.muted=!mode.muted;q('#voiceMic').classList.toggle('active',!mode.muted);if(mode.muted){stopInput();setState('muted','Микрофон выключен','Нажмите кнопку, чтобы продолжить')}else startListening()}
  function close(){mode.active=false;mode.turn++;stopInput();cancelSpeech();cancelAnimationFrame(mode.vadFrame);mode.stream?.getTracks().forEach(t=>t.stop());mode.audioContext?.close();layer.classList.remove('active');q('#voiceTranscript').classList.remove('open');document.body.style.overflow='';q('#prompt')?.focus()}
  q('#voiceMic').onclick=toggleMute;q('#voiceEnd').onclick=close;q('#voiceText').onclick=()=>q('#voiceTranscript').classList.toggle('open');q('#transcriptClose').onclick=()=>q('#voiceTranscript').classList.remove('open');q('#voiceSettings').onclick=()=>{close();settings()};
  window.novaVoice={open,close};
})();
