(()=>{if(!window.chrome?.webview)return;const pending=new Map();let seq=0,project=null,tree=[],current=null,tabs=new Map(),busy=false;
const call=(op,data={})=>new Promise((resolve,reject)=>{const id=String(++seq);pending.set(id,{resolve,reject});chrome.webview.postMessage({id,op,data})});chrome.webview.addEventListener('message',e=>{const r=e.data;if(r.eventName==='updateProgress'){handleUpdateProgress(r.progress);return}const p=pending.get(r.id);if(!p)return;pending.delete(r.id);r.ok?p.resolve(r.data):p.reject(new Error(r.error))});
document.body.insertAdjacentHTML('beforeend',`<button class="dev-launch">⌘ Project</button><section class="dev-shell"><header class="dev-top"><span class="dev-logo">NOVA <i>CODE</i></span><button class="dev-btn" data-a="open">Открыть проект</button><button class="dev-btn" data-a="refresh">↻</button><span class="dev-path">Проект не открыт</span><button class="dev-btn" data-a="close">Закрыть</button></header><main class="dev-grid"><aside class="dev-panel"><div class="dev-head">Проекты</div><div class="dev-projects"></div><div class="dev-head">Проводник <button class="dev-btn" data-a="newFile">＋Файл</button><button class="dev-btn" data-a="newFolder">＋Папка</button></div><input class="dev-search" placeholder="Поиск по проекту"><div class="dev-tree"><div class="dev-empty">Откройте папку проекта</div></div></aside><section class="dev-editor"><div class="dev-tabs"></div><textarea class="dev-code" spellcheck="false" placeholder="Выберите файл в проводнике"></textarea><div class="dev-terminal"><div class="dev-head">Терминал</div><pre>NOVA Terminal готов.</pre><form class="dev-cmd"><input placeholder="Введите команду и нажмите Enter"></form></div></section><aside class="dev-agent"><div class="dev-head">AI-разработчик · nova-1.0-nano</div><div class="dev-agent-log"><div class="dev-msg ai">Откройте проект и напишите, что нужно найти или изменить. Для записи файлов NOVA всегда покажет изменения и запросит подтверждение.</div></div><form class="dev-agent-form"><textarea placeholder="Например: найди текст «Купить сейчас» и замени на «Подробнее»"></textarea><div class="dev-actions"><label><input type="checkbox" class="dev-auto"> Agent mode</label><button class="dev-btn primary">Выполнить</button></div></form></aside></main><footer class="dev-status">Готово</footer><div class="dev-menu"></div></section>`);
const $=s=>document.querySelector(s),shell=$('.dev-shell'),code=$('.dev-code'),status=t=>$('.dev-status').textContent=t,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.querySelectorAll('[data-a="newFile"],[data-a="newFolder"],[data-a="refresh"]').forEach(x=>x.remove());
const executeBtn=$('.dev-agent-form .primary'),permissionWrap=document.createElement('div');permissionWrap.className='dev-permission-wrap';permissionWrap.innerHTML=`<button type="button" class="dev-permission-btn">Разрешения⌄</button><div class="dev-permission-list"><button data-p="ask">Спрашивать каждый раз<small>Показывать изменения перед применением</small></button><button data-p="auto">Разрешать в этом проекте<small>NOVA применяет все правки автоматически</small></button><button data-p="read">Только чтение<small>Анализировать без изменения файлов</small></button></div>`;executeBtn.before(permissionWrap);shell.insertAdjacentHTML('beforeend',`<div class="dev-approval"><div class="dev-approval-card"><div class="dev-approval-head">NOVA хочет изменить проект</div><div class="dev-approval-body"><div class="dev-approval-summary"></div><div class="dev-approval-files"></div></div><div class="dev-approval-actions"><button class="dev-deny">Отклонить</button><button class="dev-allow">Разрешить</button></div></div></div>`);
function setTaskBusy(value){busy=value;executeBtn.disabled=value;executeBtn.innerHTML=value?'<span class="dev-task-spinner"></span>':'Выполнить';agentInput&&Object.assign(agentInput,{readOnly:value})}
function permissionMode(){if(!project)return'ask';try{return JSON.parse(localStorage.getItem('nova.dev.permissions'))?.[project.root]||'ask'}catch{return'ask'}}function permissionLabel(){const x=permissionMode();$('.dev-permission-btn').textContent=(x==='auto'?'Разрешено':x==='read'?'Только чтение':'Разрешения')+'⌄';document.querySelectorAll('.dev-permission-list button').forEach(b=>b.classList.toggle('active',b.dataset.p===x))}
$('.dev-permission-btn').onclick=e=>{e.stopPropagation();$('.dev-permission-list').classList.toggle('open')};$('.dev-permission-list').onclick=e=>{const p=e.target.closest('button')?.dataset.p;if(!p||!project)return;let x={};try{x=JSON.parse(localStorage.getItem('nova.dev.permissions'))||{}}catch{}x[project.root]=p;localStorage.setItem('nova.dev.permissions',JSON.stringify(x));$('.dev-permission-list').classList.remove('open');permissionLabel()};
function approveChanges(summary,details){if(permissionMode()==='auto')return Promise.resolve(true);if(permissionMode()==='read')return Promise.resolve(false);return new Promise(resolve=>{const modal=$('.dev-approval');$('.dev-approval-summary').textContent=summary;$('.dev-approval-files').textContent=details;modal.classList.add('open');const done=x=>{modal.classList.remove('open');resolve(x)};$('.dev-deny').onclick=()=>done(false);$('.dev-allow').onclick=()=>done(true)})}
const closeBtn=$('[data-a=close]');closeBtn.insertAdjacentHTML('beforebegin',`<button class="dev-update-pill">Обновить</button><button class="dev-update-settings" title="Настройки обновлений">Обновления</button>`);shell.insertAdjacentHTML('beforeend',`<div class="dev-update-modal"><div class="dev-update-card"><h3>Обновления NOVA AI</h3><div class="dev-update-grid"><span>Текущая версия</span><b class="dev-current-version">—</b><span>Последняя версия</span><b class="dev-latest-version">—</b><input class="dev-update-url" placeholder="HTTPS-адрес latest.json"></div><div class="dev-update-progress"><i></i></div><div class="dev-update-options"><label><input type="checkbox" class="dev-auto-check"> Автоматически проверять обновления</label><label><input type="checkbox" class="dev-auto-download"> Автоматически скачивать обновления</label></div><div class="dev-update-notes"></div><div class="dev-update-error"></div><div class="dev-update-actions"><button class="dev-btn dev-update-close">Закрыть</button><button class="dev-btn dev-update-check">Проверить обновления</button><button class="dev-btn primary dev-update-save">Сохранить</button></div></div></div>`);
document.body.insertAdjacentHTML('beforeend',`<button class="main-update-pill" title="Доступно обновление NOVA AI"><span class="main-update-icon">↓</span><span class="main-update-text">Обновить</span></button>`);
const updateButtons=()=>[$('.dev-update-pill'),$('.main-update-pill')].filter(Boolean);function setUpdateButtonText(text){updateButtons().forEach(b=>b.querySelector('.main-update-text')?b.querySelector('.main-update-text').textContent=text:b.textContent=text)}
function cleanUpdateNotes(text,version){const value=String(text||'').trim();return /Р[°-ї]|С[°-ї]|[Ѓђѓљњћџ]/.test(value)?`Обновление NOVA AI ${version}.`:value}
let updateInfo=null,updateDownloading=false;function renderUpdate(i){if(!i)return;updateInfo=i;$('.dev-current-version').textContent=i.current||'—';$('.dev-latest-version').textContent=i.latest||'Обновлений нет';$('.dev-update-url').value=i.url||'';$('.dev-auto-check').checked=i.autoCheck!==false;$('.dev-auto-download').checked=!!i.autoDownload;$('.dev-update-notes').textContent=cleanUpdateNotes(i.notes,i.latest||'');updateButtons().forEach(b=>{b.classList.toggle('show',!!i.available);b.title=i.available?`Доступна версия ${i.latest}`:''});setUpdateButtonText(i.downloaded?'Перезапустить':'Обновить')}
function handleUpdateProgress(p){updateDownloading=true;$('.dev-update-progress i').style.width=p+'%';updateButtons().forEach(b=>b.classList.add('show'));setUpdateButtonText(`Загрузка ${p}%`);if(p>=100)updateDownloading=false}
async function checkUpdates(manual=false){try{$('.dev-update-error').textContent='';const info=await call('checkUpdate',{manual});renderUpdate(info);if(manual&&!info.available)$('.dev-update-error').textContent='Обновление не найдено'}catch(e){if(manual)$('.dev-update-error').textContent=e.message}}
$('.dev-update-settings').onclick=async()=>{$('.dev-update-modal').classList.add('open');try{renderUpdate(await call('updateInfo'))}catch(e){$('.dev-update-error').textContent=e.message}};$('.dev-update-close').onclick=()=>$('.dev-update-modal').classList.remove('open');$('.dev-update-check').onclick=()=>checkUpdates(true);$('.dev-update-save').onclick=async()=>{try{renderUpdate(await call('saveUpdateSettings',{url:$('.dev-update-url').value.trim(),autoCheck:$('.dev-auto-check').checked,autoDownload:$('.dev-auto-download').checked}));$('.dev-update-error').textContent='Настройки сохранены'}catch(e){$('.dev-update-error').textContent=e.message}};
async function runUpdate(){if(updateDownloading)return;try{if(updateInfo?.downloaded){await call('installUpdate');return}handleUpdateProgress(0);renderUpdate(await call('downloadUpdate'))}catch(e){updateDownloading=false;setUpdateButtonText('Повторить');$('.dev-update-error').textContent=e.message}}
$('.dev-update-pill').onclick=runUpdate;$('.main-update-pill').onclick=runUpdate;
$('.dev-launch').onclick=()=>shell.classList.add('open');$('[data-a=close]').onclick=()=>shell.classList.remove('open');
async function openProject(recent){try{if(current&&tabs.has(current)&&tabs.get(current).dirty)await save();const p=recent?await call('openRecent',{path:recent}):await call('pick');if(!p)return;project=p;localStorage.setItem('nova.dev.lastProject',p.root);rememberProject(p.root);tabs.clear();current=null;code.value='';renderTabs();$('.dev-path').textContent=p.root;status('Анализирую проект…');await refresh();await renderProjects();status('Индекс проекта готов')}catch(e){status('Ошибка: '+e.message)}}
$('[data-a=open]').onclick=()=>openProject();
function projectMeta(){try{return JSON.parse(localStorage.getItem('nova.dev.projectMeta'))||{}}catch{return{}}}function saveMeta(x){localStorage.setItem('nova.dev.projectMeta',JSON.stringify(x))}
function rememberProject(path){const m=projectMeta();m[path]={...(m[path]||{}),last:Date.now(),archived:false};saveMeta(m)}
async function renderProjects(){const native=await call('recent'),m=projectMeta(),paths=[...new Set([...native,...Object.keys(m)])].filter(p=>m[p]?.archived!==true);paths.sort((a,b)=>(m[b]?.pinned?1:0)-(m[a]?.pinned?1:0)||(m[b]?.last||0)-(m[a]?.last||0));const h=$('.dev-projects');h.innerHTML='';for(const p of paths){const row=document.createElement('div');row.className='dev-project-row'+(project?.root===p?' active':'');row.innerHTML=`<span class="dev-project-icon">${m[p]?.pinned?'◆':'▱'}</span><span class="dev-project-name">${esc(m[p]?.name||p.split(/[\\/]/).pop())}</span><button class="dev-more">⋯</button>`;row.title=p;row.onclick=e=>{if(!e.target.closest('.dev-more'))openProject(p)};row.querySelector('.dev-more').onclick=e=>showProjectMenu(e,p);h.append(row)}}
function showProjectMenu(e,path){e.stopPropagation();const m=projectMeta(),menu=$('.dev-menu');menu.innerHTML=`<button data-m="pin">⌖ ${m[path]?.pinned?'Открепить проект':'Закрепить проект'}</button><button data-m="explore">▱ Открыть в Проводнике</button><button data-m="edit">⚙ Редактировать проект</button><button data-m="archive">▣ Архивировать чаты</button><button data-m="delete">× Удалить</button>`;const r=e.target.getBoundingClientRect();menu.style.left=Math.min(r.left,innerWidth-245)+'px';menu.style.top=Math.min(r.bottom+4,innerHeight-220)+'px';menu.classList.add('open');menu.onclick=async x=>{const a=x.target.closest('button')?.dataset.m;if(!a)return;const meta=projectMeta();meta[path]=meta[path]||{};if(a==='pin')meta[path].pinned=!meta[path].pinned;if(a==='edit'){const n=prompt('Название проекта',meta[path].name||path.split(/[\\/]/).pop());if(n)meta[path].name=n}if(a==='archive')meta[path].chatsArchived=true;if(a==='delete'){meta[path].archived=true;if(project?.root===path)status('Проект убран из списка. Файлы не удалены.')}saveMeta(meta);if(a==='explore')await call('reveal',{path:''});menu.classList.remove('open');renderProjects()}}
document.addEventListener('click',e=>{if(!e.target.closest('.dev-menu')&&!e.target.closest('.dev-more'))$('.dev-menu').classList.remove('open')});
async function refresh(){if(!project)return;permissionLabel();tree=await call('tree');renderTree(tree)}
function projectFiles(nodes=tree,out=[]){for(const n of nodes){out.push(n.path.toLowerCase());if(n.dir)projectFiles(n.children||[],out)}return out}
function gameProfile(task=''){const q=task.toLowerCase(),f=projectFiles();const has=x=>f.some(p=>p.endsWith(x)||p.includes('/'+x));
 if(/gta\s*5|gta\s*v|fivem|rage\s*mp|alt:?v|файвем/.test(q)||has('fxmanifest.lua')||has('__resource.lua'))return`ПРОФИЛЬ GTA V/FiveM: определяй конкретную платформу по файлам и запросу. Для FiveM используй fxmanifest.lua, client/server/shared scripts, Lua/JS/C#, NUI HTML/CSS/JS и корректные RegisterNetEvent/TriggerServerEvent. Никогда не доверяй данным клиента: деньги, права и предметы проверяй на сервере. Не смешивай FiveM с MTA:SA, RAGE:MP и alt:V.`;
 if(/\bmta\b|mta:?sa|мта/.test(q)||has('meta.xml'))return`ПРОФИЛЬ MTA:SA (это Multiplayer для GTA San Andreas, не GTA V): используй meta.xml, client.lua/server.lua/shared.lua, element data осмотрительно, addEvent с allowRemoteTrigger и серверную валидацию client/source. Соблюдай API MTA Wiki, resourceRoot/root и ACL. Создавая ресурс, обязательно добавляй корректный meta.xml.`;
 if(/sa[- ]?mp|open\.mp|openmp|самп|pawn/.test(q)||f.some(p=>p.endsWith('.pwn')||p.endsWith('.inc'))||has('server.cfg'))return`ПРОФИЛЬ SA-MP/Open.MP: код Pawn (.pwn/.inc), callbacks, commands, dialogs, MySQL при наличии. Учитывай различия SA-MP и open.mp, не выдумывай include-файлы, проверяй bounds массивов, playerid и SQL-параметры. Для нового gamemode создай compilable .pwn и объясни необходимые includes.`;
 if(/minecraft|майнкрафт|spigot|paper|bukkit|forge|fabric|datapack|датапак/.test(q)||has('plugin.yml')||has('fabric.mod.json')||has('mods.toml')||has('pack.mcmeta')||has('server.properties')||has('pom.xml')&&f.some(p=>p.includes('src/main/java')))return`ПРОФИЛЬ Minecraft: сначала различи Paper/Spigot/Bukkit plugin, Fabric/Forge/NeoForge mod, datapack, Bedrock add-on или server config. Учитывай указанную версию Minecraft и Java. Для Paper/Spigot создавай plugin.yml и main class; для Fabric — fabric.mod.json; для datapack — pack.mcmeta и data namespace. Не выполняй Bukkit API асинхронно без необходимости и не блокируй main thread.`;
 return`ОБЩИЙ ПРОФИЛЬ: определи технологию по manifest/lock/config-файлам и сохраняй её соглашения.`}
function renderTree(nodes){const host=$('.dev-tree');host.innerHTML='';const add=(items,parent)=>items.forEach(n=>{const row=document.createElement('div');row.className='dev-node '+(n.dir?'dir':'file');row.dataset.path=n.path;row.innerHTML=(n.dir?'▸ ':'· ')+esc(n.name);parent.append(row);if(n.dir){const ch=document.createElement('div');ch.className='dev-children';ch.hidden=true;parent.append(ch);row.onclick=()=>{ch.hidden=!ch.hidden;row.firstChild.textContent=ch.hidden?'▸ ':'▾ '};add(n.children||[],ch)}else row.onclick=()=>openFile(n.path)});add(nodes,host)}
async function openFile(path,line){try{if(current&&tabs.has(current))tabs.get(current).content=code.value;let f=tabs.get(path);if(!f){f=await call('read',{path});f.dirty=false;tabs.set(path,f)}current=path;code.value=f.content;renderTabs();if(line){const a=code.value.split('\n').slice(0,line-1).join('\n').length;code.focus();code.setSelectionRange(a,a);code.scrollTop=(line-3)*20}status(path)}catch(e){status('Ошибка: '+e.message)}}
function renderTabs(){const h=$('.dev-tabs');h.innerHTML='';tabs.forEach((f,p)=>{const x=document.createElement('div');x.className='dev-tab '+(p===current?'active ':'')+(f.dirty?'dev-dirty':'');x.textContent=p.split('/').pop();x.title=p;x.onclick=()=>openFile(p);h.append(x)})}
let saveTimer;code.addEventListener('input',()=>{if(current){const f=tabs.get(current);f.content=code.value;f.dirty=true;renderTabs();clearTimeout(saveTimer);saveTimer=setTimeout(save,650)}});code.addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();code.setRangeText('  ',code.selectionStart,code.selectionEnd,'end')}});
async function save(){if(!current)return;try{const f=tabs.get(current);if(!f?.dirty)return;await call('write',{path:current,content:code.value});f.content=code.value;f.dirty=false;renderTabs();status('Автосохранено: '+current)}catch(e){status(e.message)}}
$('.dev-search').addEventListener('keydown',async e=>{if(e.key!=='Enter')return;const q=e.target.value;if(!q)return;status('Поиск: '+q);const a=await call('search',{query:q});const h=$('.dev-tree');h.innerHTML=a.length?'':'<div class="dev-empty">Ничего не найдено</div>';a.forEach(x=>{const n=document.createElement('div');n.className='dev-node';n.innerHTML=`${esc(x.path)}:${x.line}<br><small>${esc(x.text)}</small>`;n.onclick=()=>openFile(x.path,x.line);h.append(n)});status('Найдено: '+a.length)});
$('.dev-cmd').onsubmit=async e=>{e.preventDefault();const i=e.target.querySelector('input'),cmd=i.value.trim();if(!cmd)return;i.value='';const pre=$('.dev-terminal pre');pre.textContent+=`\n> ${cmd}\n`;status('Выполняю команду…');try{const r=await call('run',{command:cmd});pre.textContent+=r.output+`\n[exit ${r.code}]`;status('Команда завершена: '+r.code)}catch(x){pre.textContent+='Ошибка: '+x.message;status(x.message)}pre.scrollTop=pre.scrollHeight};
function msg(role,text){const n=document.createElement('div');n.className='dev-msg '+role;n.textContent=text;$('.dev-agent-log').append(n);n.scrollIntoView()}
$('.dev-agent-form').onsubmit=async e=>{e.preventDefault();if(busy)return;if(!project)return status('Сначала откройте проект');const input=e.target.querySelector('textarea'),task=input.value.trim();if(!task)return;input.value='';msg('user',task);setTaskBusy(true);status('NOVA анализирует задачу…');try{
 const profile=gameProfile(task),terms=await ai(`Ты AI-разработчик. ${profile} Из запроса выдели наиболее вероятную точную строку для поиска в существующем коде. Верни только строку без кавычек. Запрос: ${task}`),hits=await call('search',{query:terms.trim()}),files=[];
 for(const p of [...new Set(hits.slice(0,8).map(x=>x.path))].slice(0,5))files.push(await call('read',{path:p}));
 if(!files.length){const candidates=projectFiles().filter(p=>/(^|\/)(fxmanifest\.lua|__resource\.lua|meta\.xml|server\.cfg|plugin\.yml|fabric\.mod\.json|mods\.toml|pack\.mcmeta|pom\.xml|build\.gradle(?:\.kts)?|package\.json)$|\.(lua|pwn|inc|java|kt|cs|js|ts|html)$/.test(p)).slice(0,6);for(const p of candidates)try{files.push(await call('read',{path:p}))}catch{}}
 let prompt;
 if(files.length)prompt=`Ты NOVA, AI-разработчик. ${profile} Выполни задачу минимальными безопасными заменами. Соблюдай текущую версию API и стиль проекта. Также можешь создать новые файлы. Верни ТОЛЬКО JSON без markdown: {"summary":"...","changes":[{"path":"...","find":"точный уникальный старый фрагмент","replace":"новый фрагмент"}],"creates":[{"path":"...","content":"полное содержимое нового файла"}]}. Задача: ${task}\nФайлы:\n`+files.map(f=>`FILE ${f.path}\n${f.content}`).join('\n---\n');
 else prompt=`Ты NOVA, AI-разработчик. ${profile} В выбранном проекте нет подходящего кода — возможно папка пустая. Создай полноценный минимальный проект по запросу пользователя со всеми обязательными manifest/config/source файлами выбранной платформы. Если платформа или версия критично неоднозначна, не смешивай API: выбери наиболее вероятный современный вариант и явно назови его в summary. Для обычного сайта создай index.html, styles.css и script.js. Учитывай опечатки вроде «штмл» = HTML. Верни ТОЛЬКО JSON без markdown: {"summary":"что и для какой платформы создано","changes":[],"creates":[{"path":"относительный путь","content":"полный рабочий код"}]}. Используй только относительные безопасные пути. Запрос: ${task}`;
 const raw=await ai(prompt),plan=JSON.parse(raw.replace(/^```(?:json)?\s*|\s*```$/g,'').trim()),changes=plan.changes||[],creates=plan.creates||[];
 if(!changes.length&&!creates.length){msg('ai',plan.summary||'Изменения не требуются');return}
 const preview=[plan.summary||'Подготовлены изменения',...creates.map(c=>`СОЗДАТЬ ${c.path} (${String(c.content||'').length} символов)`),...changes.map(c=>`ИЗМЕНИТЬ ${c.path}\n- ${c.find}\n+ ${c.replace}`)].join('\n\n');msg('ai',preview);
 const allowed=await approveChanges(`Файлов для создания: ${creates.length}. Файлов для изменения: ${changes.length}.`,preview);if(!allowed){msg('ai',permissionMode()==='read'?'Режим «Только чтение»: изменения не применены.':'Изменения отклонены.');return}
 for(const c of creates){if(!c.path||typeof c.content!=='string')throw new Error('AI вернула неправильный новый файл');await call('write',{path:c.path,content:c.content});tabs.set(c.path,{path:c.path,content:c.content,dirty:false})}
 for(const c of changes){const f=files.find(x=>x.path===c.path)||await call('read',{path:c.path});const count=c.find?f.content.split(c.find).length-1:0;if(count!==1)throw new Error(`${c.path}: старый фрагмент найден ${count} раз`);const next=f.content.replace(c.find,c.replace);await call('write',{path:c.path,content:next});if(tabs.has(c.path)){tabs.get(c.path).content=next;tabs.get(c.path).dirty=false;if(current===c.path)code.value=next}}
 renderTabs();await refresh();if(creates.length)await openFile(creates[0].path);msg('ai','Готово. '+(plan.summary||'Проект создан')+'\nРезервные копии изменений сохранены в .nova/history.');status('Задача выполнена');await call('notify',{text:'Задача выполнена: '+(plan.summary||'изменения применены')})
 }catch(x){msg('ai','Ошибка: '+x.message);status('Ошибка агента')}finally{setTaskBusy(false)}};
async function ai(prompt){if(!window.puter?.ai)throw new Error('AI-модуль недоступен');const r=await puter.ai.chat([{role:'system',content:'Отвечай точно и выполняй формат пользователя.'},{role:'user',content:prompt}],{model:state?.settings?.model||'gpt-5.4-nano'});return r?.message?.content||r?.text||String(r)}
const agentInput=$('.dev-agent-form textarea');agentInput.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.ctrlKey&&!e.isComposing){e.preventDefault();e.target.form.requestSubmit()}});
(async()=>{try{await renderProjects();const recent=await call('recent'),last=localStorage.getItem('nova.dev.lastProject');const restore=recent.includes(last)?last:recent[0];if(restore){shell.classList.add('open');await openProject(restore)}}catch(e){status('Не удалось восстановить проект: '+e.message)}})();
checkUpdates(false);setInterval(()=>checkUpdates(false),3*60*60*1000);
window.addEventListener('beforeunload',e=>{if([...tabs.values()].some(x=>x.dirty)){e.preventDefault();e.returnValue=''}});
})();
