using System;using System.Collections.Generic;using System.Diagnostics;using System.IO;using System.Linq;using System.Text;using System.Threading.Tasks;using System.Web.Script.Serialization;using System.Windows.Forms;using Microsoft.Web.WebView2.Core;using Microsoft.Web.WebView2.WinForms;
namespace NovaAI {
internal sealed class ProjectHost {
 readonly Form owner;readonly WebView2 browser;readonly JavaScriptSerializer json=new JavaScriptSerializer{MaxJsonLength=16777216};readonly UpdaterService updater;string root;
 static readonly HashSet<string> ignored=new HashSet<string>(StringComparer.OrdinalIgnoreCase){"node_modules",".git","dist","build",".next",".cache","coverage",".idea",".venv","venv","bin","obj",".nova"};
 static readonly HashSet<string> binary=new HashSet<string>(StringComparer.OrdinalIgnoreCase){".png",".jpg",".jpeg",".gif",".webp",".ico",".zip",".7z",".rar",".exe",".dll",".pdb",".pdf",".mp3",".mp4",".woff",".woff2",".ttf"};
 public ProjectHost(Form owner,WebView2 browser){this.owner=owner;this.browser=browser;updater=new UpdaterService(owner,p=>browser.CoreWebView2.PostWebMessageAsJson(json.Serialize(new{eventName="updateProgress",progress=p})));browser.CoreWebView2.WebMessageReceived+=OnMessage;}
 async void OnMessage(object s,CoreWebView2WebMessageReceivedEventArgs e){Dictionary<string,object> r=null;string id="";try{r=json.Deserialize<Dictionary<string,object>>(e.WebMessageAsJson);id=Get(r,"id");var d=r.ContainsKey("data")?r["data"] as Dictionary<string,object>:new Dictionary<string,object>();Reply(id,true,await Execute(Get(r,"op"),d),null);}catch(Exception ex){Reply(id,false,null,ex.Message);}}
 async Task<object> Execute(string op,Dictionary<string,object>d){switch(op){
 case "pick":using(var x=new FolderBrowserDialog{Description="Выберите папку проекта NOVA",ShowNewFolderButton=true}){if(x.ShowDialog(owner)!=DialogResult.OK)return null;root=Path.GetFullPath(x.SelectedPath);SaveRecent();return new{root,name=Path.GetFileName(root)};}
 case "openRecent":root=Path.GetFullPath(Get(d,"path"));EnsureRoot();SaveRecent();return new{root,name=Path.GetFileName(root)};
 case "recent":return LoadRecent();case "tree":EnsureRoot();return Tree(root,0);
 case "read":{var p=Safe(Get(d,"path"));var f=new FileInfo(p);if(!f.Exists)throw new FileNotFoundException();if(f.Length>2097152||binary.Contains(f.Extension))throw new IOException("Этот файл нельзя открыть как текст");return new{path=Rel(p),content=File.ReadAllText(p,Encoding.UTF8),modified=f.LastWriteTimeUtc.ToString("o")};}
 case "search":return Search(Get(d,"query"));case "write":return Write(Get(d,"path"),Get(d,"content"));
 case "createFile":{var p=Safe(Get(d,"path"));Directory.CreateDirectory(Path.GetDirectoryName(p));if(File.Exists(p))throw new IOException("Файл уже существует");File.WriteAllText(p,"",new UTF8Encoding(false));return true;}
 case "createFolder":Directory.CreateDirectory(Safe(Get(d,"path")));return true;
 case "rename":{var a=Safe(Get(d,"path"));var b=Safe(Get(d,"newPath"));if(File.Exists(a))File.Move(a,b);else if(Directory.Exists(a))Directory.Move(a,b);else throw new IOException("Путь не найден");return true;}
 case "delete":{var p=Safe(Get(d,"path"));Backup(p);if(File.Exists(p))File.Delete(p);else if(Directory.Exists(p))Directory.Delete(p,true);return true;}
 case "run":return await Run(Get(d,"command"));case "reveal":Process.Start("explorer.exe","/select,\""+Safe(Get(d,"path"))+"\"");return true;
 case "notify":{if(owner.WindowState==FormWindowState.Minimized||!owner.ContainsFocus){var n=new NotifyIcon{Icon=owner.Icon,Visible=true,BalloonTipTitle="NOVA AI",BalloonTipText=string.IsNullOrWhiteSpace(Get(d,"text"))?"Задача выполнена":Get(d,"text"),BalloonTipIcon=ToolTipIcon.Info};n.ShowBalloonTip(5000);var timer=new Timer{Interval=7000};timer.Tick+=(s,e)=>{timer.Stop();n.Visible=false;n.Dispose();timer.Dispose();};timer.Start();}return true;}
 case "updateInfo":return updater.Info();case "checkUpdate":return await updater.Check(Get(d,"manual").Equals("true",StringComparison.OrdinalIgnoreCase));case "downloadUpdate":return await updater.Download();case "saveUpdateSettings":updater.Save(d);return updater.Info();case "installUpdate":updater.Install();return true;
 case "exploreProject":{var p=Path.GetFullPath(Get(d,"path"));if(!LoadRecent().Any(x=>x.Equals(p,StringComparison.OrdinalIgnoreCase)))throw new UnauthorizedAccessException("Проект отсутствует в недавних");Process.Start("explorer.exe",p);return true;}
 default:throw new InvalidOperationException("Неизвестная операция "+op);}}
 object Tree(string dir,int depth){if(depth>10)return new object[0];var a=new List<object>();try{foreach(var p in Directory.EnumerateFileSystemEntries(dir).OrderBy(x=>File.Exists(x)).ThenBy(Path.GetFileName)){var n=Path.GetFileName(p);if(IsHidden(p))continue;if(Directory.Exists(p)){if(!ignored.Contains(n))a.Add(new{name=n,path=Rel(p),dir=true,children=Tree(p,depth+1)});}else{var f=new FileInfo(p);if(f.Length<5242880&&!binary.Contains(f.Extension))a.Add(new{name=n,path=Rel(p),dir=false,size=f.Length});}}}catch{}return a;}
 object Search(string q){EnsureRoot();var a=new List<object>();if(string.IsNullOrWhiteSpace(q))return a;foreach(var f in Files()){try{int n=0;foreach(var line in File.ReadLines(f)){n++;if(line.IndexOf(q,StringComparison.OrdinalIgnoreCase)>=0){a.Add(new{path=Rel(f),line=n,text=line.Trim()});if(a.Count>=200)return a;}}}catch{}}return a;}
 object Write(string rel,string text){var p=Safe(rel);string before=File.Exists(p)?File.ReadAllText(p):"";Backup(p);Directory.CreateDirectory(Path.GetDirectoryName(p));var t=p+".nova-tmp";File.WriteAllText(t,text,new UTF8Encoding(false));if(File.Exists(p))File.Replace(t,p,null);else File.Move(t,p);return new{path=rel,beforeLength=before.Length,afterLength=text.Length};}
 async Task<object> Run(string command){EnsureRoot();return await Task.Run<object>(()=>{var i=new ProcessStartInfo("cmd.exe","/d /s /c \""+command+"\""){WorkingDirectory=root,UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true,StandardOutputEncoding=Encoding.UTF8,StandardErrorEncoding=Encoding.UTF8};using(var p=Process.Start(i)){var o=p.StandardOutput.ReadToEnd()+p.StandardError.ReadToEnd();if(!p.WaitForExit(120000)){p.Kill();throw new TimeoutException("Команда остановлена");}return new{output=o,code=p.ExitCode};}});}
 IEnumerable<string> Files(){var s=new Stack<string>();s.Push(root);while(s.Count>0){var d=s.Pop();string[] ds,fs;try{ds=Directory.GetDirectories(d);fs=Directory.GetFiles(d);}catch{continue;}foreach(var x in ds)if(!ignored.Contains(Path.GetFileName(x))&&!IsHidden(x))s.Push(x);foreach(var f in fs){var i=new FileInfo(f);if(i.Length<2097152&&!binary.Contains(i.Extension)&&!IsHidden(f))yield return f;}}}
 void Backup(string p){if(!File.Exists(p))return;var t=Path.Combine(root,".nova","history",DateTime.UtcNow.ToString("yyyyMMdd-HHmmssfff"),Rel(p));Directory.CreateDirectory(Path.GetDirectoryName(t));File.Copy(p,t,true);}
 string Safe(string x){EnsureRoot();var p=Path.GetFullPath(Path.Combine(root,x??""));var pre=root.TrimEnd('\\')+"\\";if(p!=root&&!p.StartsWith(pre,StringComparison.OrdinalIgnoreCase))throw new UnauthorizedAccessException("Путь вне проекта");return p;}string Rel(string p)=>p.Substring(root.TrimEnd('\\').Length).TrimStart('\\').Replace('\\','/');
 bool IsHidden(string p){try{return(File.GetAttributes(p)&FileAttributes.Hidden)!=0;}catch{return true;}}void EnsureRoot(){if(string.IsNullOrEmpty(root)||!Directory.Exists(root))throw new InvalidOperationException("Сначала откройте проект");}string Get(Dictionary<string,object>d,string k)=>d!=null&&d.ContainsKey(k)&&d[k]!=null?Convert.ToString(d[k]):"";void Reply(string id,bool ok,object data,string error)=>browser.CoreWebView2.PostWebMessageAsJson(json.Serialize(new{id,ok,data,error}));
 string RecentFile=>Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"NOVA AI","recent-projects.txt");IEnumerable<string> LoadRecent()=>File.Exists(RecentFile)?File.ReadAllLines(RecentFile).Where(Directory.Exists):Enumerable.Empty<string>();void SaveRecent(){Directory.CreateDirectory(Path.GetDirectoryName(RecentFile));var a=LoadRecent().Where(x=>!x.Equals(root,StringComparison.OrdinalIgnoreCase)).Take(7).ToList();a.Insert(0,root);File.WriteAllLines(RecentFile,a);}
}}
