using System;using System.Collections.Generic;using System.Diagnostics;using System.IO;using System.IO.Compression;using System.Net;using System.Reflection;using System.Security.Cryptography;using System.Text;using System.Threading.Tasks;using System.Web.Script.Serialization;using System.Windows.Forms;
namespace NovaAI {
internal delegate void UpdateProgressCallback(int value);
internal sealed class UpdaterService {
 readonly Form owner;readonly UpdateProgressCallback progress;readonly JavaScriptSerializer json=new JavaScriptSerializer();UpdateManifest latest;string downloaded;
 string DataDir=>Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"NOVA AI","Updater");string SettingsFile=>Path.Combine(DataDir,"settings.json");
 internal UpdaterService(Form owner,UpdateProgressCallback progress){this.owner=owner;this.progress=progress;ServicePointManager.SecurityProtocol=SecurityProtocolType.Tls12;}
 internal object Info(){var s=Settings();return new{current=CurrentVersion(),latest=latest?.version,available=latest!=null&&Newer(latest.version,CurrentVersion()),notes=latest?.notes,url=s.url,autoCheck=s.autoCheck,autoDownload=s.autoDownload,downloaded=!string.IsNullOrEmpty(downloaded)&&File.Exists(downloaded)};}
 internal async Task<object> Check(bool manual){var s=Settings();if(!manual&&!s.autoCheck)return Info();try{if(!Uri.TryCreate(s.url,UriKind.Absolute,out var uri)||uri.Scheme!="https")throw new InvalidOperationException("Адрес обновлений должен использовать HTTPS");using(var wc=new WebClient()){wc.Headers[HttpRequestHeader.UserAgent]="NOVA-AI-Updater/1.0";var raw=await wc.DownloadStringTaskAsync(uri);latest=json.Deserialize<UpdateManifest>(raw);}ValidateManifest();if(Newer(latest.version,CurrentVersion())&&s.autoDownload)await Download();return Info();}catch{if(manual)throw;return Info();}}
 internal void Save(Dictionary<string,object>d){Directory.CreateDirectory(DataDir);var s=Settings();if(d.ContainsKey("url"))s.url=Convert.ToString(d["url"]);if(d.ContainsKey("autoCheck"))s.autoCheck=Convert.ToBoolean(d["autoCheck"]);if(d.ContainsKey("autoDownload"))s.autoDownload=Convert.ToBoolean(d["autoDownload"]);File.WriteAllText(SettingsFile,json.Serialize(s),new UTF8Encoding(false));}
 internal async Task<object> Download(){ValidateManifest();Directory.CreateDirectory(DataDir);var uri=new Uri(latest.download);string ext=Path.GetExtension(uri.AbsolutePath).ToLowerInvariant();if(ext!=".zip"&&ext!=".exe")throw new InvalidOperationException("Разрешены только ZIP или EXE обновления");downloaded=Path.Combine(DataDir,"NOVA-AI-"+latest.version+ext);using(var wc=new WebClient()){wc.Headers[HttpRequestHeader.UserAgent]="NOVA-AI-Updater/1.0";wc.DownloadProgressChanged+=(s,e)=>progress(e.ProgressPercentage);await wc.DownloadFileTaskAsync(uri,downloaded);}var hash=Sha256(downloaded);if(!hash.Equals(latest.sha256,StringComparison.OrdinalIgnoreCase)){File.Delete(downloaded);downloaded=null;throw new InvalidDataException("Контрольная сумма обновления не совпала");}progress(100);return Info();}
 internal void Install(){if(string.IsNullOrEmpty(downloaded)||!File.Exists(downloaded))throw new FileNotFoundException("Обновление ещё не загружено");if(!Sha256(downloaded).Equals(latest.sha256,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("Файл обновления повреждён");if(Path.GetExtension(downloaded).Equals(".exe",StringComparison.OrdinalIgnoreCase)){Process.Start(new ProcessStartInfo(downloaded){UseShellExecute=true});owner.BeginInvoke(new MethodInvoker(owner.Close));return;}string stage=Path.Combine(DataDir,"stage-"+latest.version);if(Directory.Exists(stage))Directory.Delete(stage,true);ZipFile.ExtractToDirectory(downloaded,stage);string exe=Path.Combine(stage,"NOVA AI.exe");if(!File.Exists(exe))throw new InvalidDataException("В архиве отсутствует NOVA AI.exe");string app=AppDomain.CurrentDomain.BaseDirectory.TrimEnd('\\');string cmd=Path.Combine(DataDir,"install-update.cmd");string body="@echo off\r\ntimeout /t 2 /nobreak >nul\r\nrobocopy \""+stage+"\" \""+app+"\" /E /R:10 /W:1 >nul\r\nstart \"\" \""+Path.Combine(app,"NOVA AI.exe")+"\"\r\ndel \"%~f0\"\r\n";File.WriteAllText(cmd,body,Encoding.Default);Process.Start(new ProcessStartInfo(cmd){UseShellExecute=true,WindowStyle=ProcessWindowStyle.Hidden});owner.BeginInvoke(new MethodInvoker(owner.Close));}
 void ValidateManifest(){if(latest==null||string.IsNullOrWhiteSpace(latest.version)||string.IsNullOrWhiteSpace(latest.download)||string.IsNullOrWhiteSpace(latest.sha256))throw new InvalidDataException("Сервер вернул неправильный манифест");if(!Uri.TryCreate(latest.download,UriKind.Absolute,out var u)||u.Scheme!="https")throw new InvalidDataException("Обновление должно загружаться по HTTPS");if(latest.sha256.Length!=64)throw new InvalidDataException("Неправильная SHA-256 сумма");}
 UpdateSettings Settings(){try{if(File.Exists(SettingsFile))return json.Deserialize<UpdateSettings>(File.ReadAllText(SettingsFile));}catch{}return new UpdateSettings();}string CurrentVersion()=>Assembly.GetExecutingAssembly().GetName().Version.ToString(3);bool Newer(string a,string b)=>Version.TryParse(a,out var x)&&Version.TryParse(b,out var y)&&x>y;string Sha256(string p){using(var h=SHA256.Create())using(var f=File.OpenRead(p))return BitConverter.ToString(h.ComputeHash(f)).Replace("-","");}
 internal sealed class UpdateManifest{public string version{get;set;}public string download{get;set;}public string sha256{get;set;}public string notes{get;set;}}
 internal sealed class UpdateSettings{public string url{get;set;}="https://raw.githubusercontent.com/Niostv/NOVA-AI-Releases/main/latest.json";public bool autoCheck{get;set;}=true;public bool autoDownload{get;set;}=false;}
}}
